import dedent from "dedent";

export default {
  SUGGESTIONS: [
    "Build a To-Do App",
    "Design a Budget Tracker",
    "Make a Gym Dashboard",
    "Develop a History Quiz App",
    "Design a Login & Signup Page",
    "Build a Recipe Sharing Website",
    "Make an E-Commerce Store",
    "Build a Travel Blog",
  ],

  HERO_HEADING: "Craft What You Imagine",
  HERO_DESC: "Create stunning websites without touching a single line of code",

  INPUT_PLACEHOLDER: "Write your idea, we’ll make it real…",

  DIALOGS: {
    SIGNIN: {
      HEADING: "Continue With Crafta",
      SUBHEADING:
        "To use Crafta you must log into an existing account or create one.",
    },
    GET_STARTED: {
      HEADING: "Get Started With Crafta",
      SUBHEADING:
        "Create a new account to unlock all features and start building amazing projects!",
    },
  },

  DEFAULT_FILE: {
    // --- Project Configuration ---

    "/package.json": {
      code: dedent`
    {
      "name": "crafta-ai-website",
      "private": true,
      "version": "1.0.0",
      "type": "module",
      "scripts": {
        "dev": "vite",
        "build": "vite build",
        "preview": "vite preview"
      },
      "dependencies": {
        "react": "^18.3.1",
        "react-dom": "^18.3.1",
        "react-router-dom": "^6.25.0",
        "lucide-react": "^0.400.0",
        "tailwind-merge": "^2.5.0",
        "uuid": "^9.0.3"
      },
      "devDependencies": {
        "@tailwindcss/vite": "^4.0.0-alpha.13",
        "@vitejs/plugin-react": "^4.3.1",
        "tailwindcss": "^4.0.0-beta.2",
        "vite": "^5.4.0"
      }
    }
    `,
    },

    "/vite.config.js": {
      code: dedent`
    import { defineConfig } from 'vite'
    import react from '@vitejs/plugin-react'
    import tailwindcss from '@tailwindcss/vite'

    // https://vitejs.dev/config/
    export default defineConfig({
      plugins: [
        react(),
        tailwindcss(),
      ],
    })
    `,
    },

    "/.gitignore": {
      code: dedent`
    # Logs
    logs
    *.log
    npm-debug.log*

    # Node
    node_modules
    dist
    dist-ssr
    *.local

    # Envs
    .env
    .env*

    # IDEs
    .idea
    .vscode
    `,
    },

    // --- Public Assets ---

    "/public/index.html": {
      code: dedent`
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Generated by Crafta AI</title>
      </head>
      <body>
        <div id="root"></div>
        <script type="module" src="/src/main.jsx"></script>
      </body>
    </html>
    `,
    },

    // --- Source Code ---

    "/src/main.jsx": {
      code: dedent`
    import React from 'react';
    import ReactDOM from 'react-dom/client';
    import App from './App.jsx';
    import './index.css';

    ReactDOM.createRoot(document.getElementById('root')).render(
      <React.StrictMode>
        <App />
      </React.StrictMode>,
    )
    `,
    },

    "/src/index.css": {
      code: dedent`
    @import 'tailwindcss';
    `,
    },

    "/src/App.jsx": {
      code: dedent`
    import React from 'react';

    export default function App() {
      return (
        <main className="flex items-center justify-center min-h-screen bg-gray-900 text-gray-200">
          <div className="text-center">
            <h1 className="text-4xl font-bold tracking-wider animate-pulse">
              Crafta is Crafting your Website
            </h1>
            <p className="text-gray-400 mt-2">Please wait a moment...</p>
          </div>
        </main>
      );
    }
    `,
    },

    "/README.md": {
      code: dedent`
    # ✨ Your New Website ✨

    This project was generated by **Crafta AI**. 
    It's a modern, blazing-fast web application ready for customization.

    ---

    ## 🛠️ Technologies Used

    This project is built with a modern, production-ready stack:

    - **⚛️ React 18:** For building dynamic user interfaces.
    - **⚡ Vite:** A next-generation frontend build tool for lightning-fast development.
    - **🌬️ Tailwind CSS v4:** A utility-first CSS framework for rapid, custom styling without leaving your HTML.
    - **🎨 Lucide Icons:** Beautiful and consistent open-source icons.

    ---

    ## 📂 Project Structure

    The project follows a standard Vite + React setup:

    - \`public/\`: Contains static assets like \`index.html\`.
    - \`src/\`: Contains all the application source code.
      - \`App.jsx\`: The main root component of the application.
      - \`main.jsx\`: The entry point that renders the React app into the DOM.
      - \`index.css\`: The global stylesheet where Tailwind CSS is initialized.
    - \`package.json\`: Lists all project dependencies and scripts.
    - \`vite.config.js\`: Configuration for the Vite build tool.

    ---

    ## 🚀 Getting Started

    To run this project locally:

    1.  **Install dependencies:**
        \`\`\`bash
        npm install
        \`\`\`
    2.  **Start the development server:**
        \`\`\`bash
        npm run dev
        \`\`\`
    `,
    },
  },

  DEPENDANCY: {
    postcss: "^8.4.0",
    tailwindcss: "^4.0.0",
    autoprefixer: "^10.4.21",
    uuid: "^11.1.0",
    "tailwind-merge": "^3.3.1",
    "lucide-react": "^0.539.0",
    "react-router-dom": "^7.7.1",
    firebase: "^12.1.0",
    "@google/generative-ai": "^0.24.1",
    "date-fns": "^4.1.0",
    "react-chartjs-2": "^5.3.0",
    "chart.js": "^4.4.7",
  },
};
